// GENERATED BY dbtogo (github.com/kdar/dbtogo); DO NOT EDIT
// ---args: /home/h4ck3rm1k3/goroot_sql/bin/kdb sqlite3 taginfo-languages.db
package model

type Arger interface {
  Args() []interface{}
}

var InsertStmts = map[string]string{
  "Source":                        "INSERT INTO Source (Id,Name,Updatestart,Updateend,Datauntil) VALUES (?, ?, ?, ?, ?)",
  "Stats":                         "INSERT INTO Stats (Key,Value) VALUES (?, ?)",
  "Subtags":                       "INSERT INTO Subtags (Stype,Subtag,Added,Suppressscript,Scope,Description,Prefix) VALUES (?, ?, ?, ?, ?, ?, ?)",
  "Unicodescripts":                "INSERT INTO Unicodescripts (Script,Name) VALUES (?, ?)",
  "Unicodecodepointscriptmapping": "INSERT INTO Unicodecodepointscriptmapping (Codepointfrom,Codepointto,Name) VALUES (?, ?, ?)",
  "Sqlitestat1":                   "INSERT INTO Sqlitestat1 (Tbl,Idx,Stat) VALUES (?, ?, ?)",
}
var SelectStmts = map[string]string{
  "Source":                        "SELECT Id,Name,Updatestart,Updateend,Datauntil FROM Source",
  "Stats":                         "SELECT Key,Value FROM Stats",
  "Subtags":                       "SELECT Stype,Subtag,Added,Suppressscript,Scope,Description,Prefix FROM Subtags",
  "Unicodescripts":                "SELECT Script,Name FROM Unicodescripts",
  "Unicodecodepointscriptmapping": "SELECT Codepointfrom,Codepointto,Name FROM Unicodecodepointscriptmapping",
  "Sqlitestat1":                   "SELECT Tbl,Idx,Stat FROM Sqlitestat1",
}

type Source struct {
  Id          string
  Name        string
  Updatestart string
  Updateend   string
  Datauntil   string
}

func (t *Source) Args() []interface{} {
  return []interface{}{&t.Id, &t.Name, &t.Updatestart, &t.Updateend, &t.Datauntil}
}

type Stats struct {
  Key   string
  Value string
}

func (t *Stats) Args() []interface{} { return []interface{}{&t.Key, &t.Value} }

type Subtags struct {
  Stype          string
  Subtag         string
  Added          string
  Suppressscript string
  Scope          string
  Description    string
  Prefix         string
}

func (t *Subtags) Args() []interface{} {
  return []interface{}{&t.Stype, &t.Subtag, &t.Added, &t.Suppressscript, &t.Scope, &t.Description, &t.Prefix}
}

type Unicodescripts struct {
  Script string
  Name   string
}

func (t *Unicodescripts) Args() []interface{} { return []interface{}{&t.Script, &t.Name} }

type Unicodecodepointscriptmapping struct {
  Codepointfrom string
  Codepointto   string
  Name          string
}

func (t *Unicodecodepointscriptmapping) Args() []interface{} {
  return []interface{}{&t.Codepointfrom, &t.Codepointto, &t.Name}
}

type Sqlitestat1 struct {
  Tbl  string
  Idx  string
  Stat string
}

func (t *Sqlitestat1) Args() []interface{} { return []interface{}{&t.Tbl, &t.Idx, &t.Stat} }
